version: '3'

services:
  discovery:
    image: troy/discovery
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - service_network
    ports:
      - "8761:8761"
    environment:
      RUN_ARGS: "
        --spring.profiles.active=docker
      "
      JAVA_OPTS: "
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        -Xmx300m
        -Xms100m
      "

  admin:
    image: troy/admin
    restart: always
    depends_on:
      - discovery
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - service_network
    ports:
      - "9999:9999"
    environment:
      RUN_ARGS: "
        --spring.profiles.active=docker
      "
      JAVA_OPTS: "
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        -Xmx300m
        -Xms100m
      "

  gateway:
    image: troy/gateway
    restart: always
    depends_on:
      - discovery
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - service_network
    ports:
      - "4000:4000"
    environment:
      RUN_ARGS: "
        --spring.profiles.active=docker
      "
      JAVA_OPTS: "
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        -Xmx300m
        -Xms100m
      "

  oauth:
    image: troy/oauth
    restart: always
    depends_on:
      - discovery
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - service_network
    ports:
      - "8081:8081"
    environment:
      RUN_ARGS: "
        --spring.profiles.active=docker
      "
      JAVA_OPTS: "
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        -Xmx300m
        -Xms100m
      "

  web:
    image: troy/web
    restart: always
    depends_on:
      - discovery
      - oauth
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - service_network
    ports:
      - "8080:8080"
    environment:
      RUN_ARGS: "
        --spring.profiles.active=docker
      "
      JAVA_OPTS: "
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        -Xmx300m
        -Xms100m
      "

networks:
  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
