spring.application.name: spring-cloud-discovery-service

server.port: 8761

eureka.client:
  register-with-eureka: true
  fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS